// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h60300000, 32'h60300003}
    }},
    '{"rv_dm__mem", '{
        '{32'h00010000, 32'h00010fff}
    }},
    '{"rom_ctrl__rom", '{
        '{32'h00008000, 32'h0000ffff}
    }},
    '{"rom_ctrl__regs", '{
        '{32'h60600000, 32'h6060007f}
    }},
    '{"peri", '{
        '{32'h40480000, 32'h404803ff},
        '{32'h80000000, 32'hbfffffff}
    }},
    '{"spi_host0", '{
        '{32'h70100000, 32'h7010003f}
    }},
    '{"rv_plic", '{
        '{32'h48000000, 32'h4fffffff}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h60700000, 32'h607000ff}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h60200000, 32'h6020001f}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1001ffff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h60400000, 32'h6040001f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h60000000, 32'h60000fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rom_ctrl__rom",
        "rv_dm__mem",
        "sram_ctrl_main__ram",
        "sram_ctrl_ret_aon__ram"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "peri",
        "spi_host0",
        "rv_plic",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "peri",
        "spi_host0",
        "rv_plic",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs"}}
};
