// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `topgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h60300000, 32'h60300003}
    }},
    '{"rv_dm__mem", '{
        '{32'h00010000, 32'h00010fff}
    }},
    '{"rom_ctrl__rom", '{
        '{32'h00008000, 32'h0000ffff}
    }},
    '{"rom_ctrl__regs", '{
        '{32'h60600000, 32'h6060007f}
    }},
    '{"spi_host0", '{
        '{32'h70100000, 32'h7010003f}
    }},
    '{"rv_plic", '{
        '{32'h48000000, 32'h4fffffff}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h60700000, 32'h607000ff}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h60200000, 32'h6020001f}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1001ffff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h60400000, 32'h6040001f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h60000000, 32'h60000fff}
    }},
    '{"uart0", '{
        '{32'h80000000, 32'h8000003f}
    }},
    '{"i2c0", '{
        '{32'h80030000, 32'h8003007f}
    }},
    '{"pwm_aon", '{
        '{32'h80090000, 32'h8009007f}
    }},
    '{"gpio", '{
        '{32'h80010000, 32'h8001003f}
    }},
    '{"spi_device", '{
        '{32'h80020000, 32'h80021fff}
    }},
    '{"rv_timer", '{
        '{32'h90010000, 32'h900101ff}
    }},
    '{"pwrmgr_aon", '{
        '{32'h80040000, 32'h8004007f}
    }},
    '{"rstmgr_aon", '{
        '{32'h80050000, 32'h8005007f}
    }},
    '{"clkmgr_aon", '{
        '{32'h80060000, 32'h8006007f}
    }},
    '{"pinmux_aon", '{
        '{32'h800a0000, 32'h800a0fff}
    }},
    '{"otp_ctrl__core", '{
        '{32'ha0000000, 32'ha0001fff}
    }},
    '{"otp_ctrl__prim", '{
        '{32'hb0001000, 32'hb000101f}
    }},
    '{"lc_ctrl", '{
        '{32'h800c0000, 32'h800c00ff}
    }},
    '{"aon_timer_aon", '{
        '{32'h800b0000, 32'h800b003f}
    }},
    '{"sysrst_ctrl_aon", '{
        '{32'h80070000, 32'h800700ff}
    }},
    '{"adc_ctrl_aon", '{
        '{32'h80080000, 32'h8008007f}
    }},
    '{"ast", '{
        '{32'h40480000, 32'h404803ff}
    }}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rom_ctrl__rom",
        "rv_dm__mem",
        "sram_ctrl_main__ram",
        "sram_ctrl_ret_aon__ram"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "uart0",
        "i2c0",
        "gpio",
        "spi_device",
        "rv_timer",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "otp_ctrl__core",
        "otp_ctrl__prim",
        "lc_ctrl",
        "ast",
        "aon_timer_aon",
        "adc_ctrl_aon",
        "sysrst_ctrl_aon",
        "pwm_aon",
        "spi_host0",
        "rv_plic",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "rv_dm__mem",
        "rv_dm__regs",
        "sram_ctrl_main__ram",
        "uart0",
        "i2c0",
        "gpio",
        "spi_device",
        "rv_timer",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "otp_ctrl__core",
        "otp_ctrl__prim",
        "lc_ctrl",
        "ast",
        "aon_timer_aon",
        "adc_ctrl_aon",
        "sysrst_ctrl_aon",
        "pwm_aon",
        "spi_host0",
        "rv_plic",
        "sram_ctrl_main__regs",
        "rv_core_ibex__cfg",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs"}}
};
