// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"uart0", '{
        '{32'h80000000, 32'h8000003f}
    }},
    '{"i2c0", '{
        '{32'h80030000, 32'h8003007f}
    }},
    '{"pwm_aon", '{
        '{32'h80090000, 32'h8009007f}
    }},
    '{"gpio", '{
        '{32'h80010000, 32'h8001003f}
    }},
    '{"spi_device", '{
        '{32'h80020000, 32'h80021fff}
    }},
    '{"rv_timer", '{
        '{32'h90010000, 32'h900101ff}
    }},
    '{"pwrmgr_aon", '{
        '{32'h80040000, 32'h8004007f}
    }},
    '{"rstmgr_aon", '{
        '{32'h80050000, 32'h8005007f}
    }},
    '{"clkmgr_aon", '{
        '{32'h80060000, 32'h8006007f}
    }},
    '{"pinmux_aon", '{
        '{32'h800a0000, 32'h800a0fff}
    }},
    '{"otp_ctrl__core", '{
        '{32'ha0000000, 32'ha0001fff}
    }},
    '{"otp_ctrl__prim", '{
        '{32'hb0001000, 32'hb000101f}
    }},
    '{"lc_ctrl", '{
        '{32'h800c0000, 32'h800c00ff}
    }},
    '{"aon_timer_aon", '{
        '{32'h800b0000, 32'h800b003f}
    }},
    '{"sysrst_ctrl_aon", '{
        '{32'h80070000, 32'h800700ff}
    }},
    '{"adc_ctrl_aon", '{
        '{32'h80080000, 32'h8008007f}
    }},
    '{"ast", '{
        '{32'h40480000, 32'h404803ff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"main", 0, '{
        "uart0",
        "i2c0",
        "gpio",
        "spi_device",
        "rv_timer",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "otp_ctrl__core",
        "otp_ctrl__prim",
        "lc_ctrl",
        "ast",
        "aon_timer_aon",
        "adc_ctrl_aon",
        "sysrst_ctrl_aon",
        "pwm_aon"}}
};
