// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings
//! - Pinmux Pin/Select Names
//! - Power Manager Wakeups

use core::convert::TryFrom;

/// Peripheral base address for data_proc in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const DATA_PROC_BASE_ADDR: usize = 0x40000000;

/// Peripheral size for data_proc in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #DATA_PROC_BASE_ADDR and
/// `DATA_PROC_BASE_ADDR + DATA_PROC_SIZE_BYTES`.
pub const DATA_PROC_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for uart0 in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const UART0_BASE_ADDR: usize = 0x44000000;

/// Peripheral size for uart0 in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #UART0_BASE_ADDR and
/// `UART0_BASE_ADDR + UART0_SIZE_BYTES`.
pub const UART0_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for gpio in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const GPIO_BASE_ADDR: usize = 0x40040000;

/// Peripheral size for gpio in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #GPIO_BASE_ADDR and
/// `GPIO_BASE_ADDR + GPIO_SIZE_BYTES`.
pub const GPIO_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for spi_device in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SPI_DEVICE_BASE_ADDR: usize = 0x40050000;

/// Peripheral size for spi_device in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SPI_DEVICE_BASE_ADDR and
/// `SPI_DEVICE_BASE_ADDR + SPI_DEVICE_SIZE_BYTES`.
pub const SPI_DEVICE_SIZE_BYTES: usize = 0x2000;

/// Peripheral base address for i2c0 in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const I2C0_BASE_ADDR: usize = 0x40080000;

/// Peripheral size for i2c0 in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #I2C0_BASE_ADDR and
/// `I2C0_BASE_ADDR + I2C0_SIZE_BYTES`.
pub const I2C0_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for pattgen in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PATTGEN_BASE_ADDR: usize = 0x400E0000;

/// Peripheral size for pattgen in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PATTGEN_BASE_ADDR and
/// `PATTGEN_BASE_ADDR + PATTGEN_SIZE_BYTES`.
pub const PATTGEN_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for rv_timer in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_TIMER_BASE_ADDR: usize = 0x40100000;

/// Peripheral size for rv_timer in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_TIMER_BASE_ADDR and
/// `RV_TIMER_BASE_ADDR + RV_TIMER_SIZE_BYTES`.
pub const RV_TIMER_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for core device on otp_ctrl in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_CTRL_CORE_BASE_ADDR: usize = 0x40130000;

/// Peripheral size for core device on otp_ctrl in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_CTRL_CORE_BASE_ADDR and
/// `OTP_CTRL_CORE_BASE_ADDR + OTP_CTRL_CORE_SIZE_BYTES`.
pub const OTP_CTRL_CORE_SIZE_BYTES: usize = 0x2000;

/// Peripheral base address for prim device on otp_ctrl in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_CTRL_PRIM_BASE_ADDR: usize = 0x40132000;

/// Peripheral size for prim device on otp_ctrl in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_CTRL_PRIM_BASE_ADDR and
/// `OTP_CTRL_PRIM_BASE_ADDR + OTP_CTRL_PRIM_SIZE_BYTES`.
pub const OTP_CTRL_PRIM_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for lc_ctrl in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const LC_CTRL_BASE_ADDR: usize = 0x40140000;

/// Peripheral size for lc_ctrl in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #LC_CTRL_BASE_ADDR and
/// `LC_CTRL_BASE_ADDR + LC_CTRL_SIZE_BYTES`.
pub const LC_CTRL_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for alert_handler in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ALERT_HANDLER_BASE_ADDR: usize = 0x40150000;

/// Peripheral size for alert_handler in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ALERT_HANDLER_BASE_ADDR and
/// `ALERT_HANDLER_BASE_ADDR + ALERT_HANDLER_SIZE_BYTES`.
pub const ALERT_HANDLER_SIZE_BYTES: usize = 0x800;

/// Peripheral base address for spi_host0 in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SPI_HOST0_BASE_ADDR: usize = 0x40300000;

/// Peripheral size for spi_host0 in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SPI_HOST0_BASE_ADDR and
/// `SPI_HOST0_BASE_ADDR + SPI_HOST0_SIZE_BYTES`.
pub const SPI_HOST0_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for pwrmgr_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PWRMGR_AON_BASE_ADDR: usize = 0x40400000;

/// Peripheral size for pwrmgr_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PWRMGR_AON_BASE_ADDR and
/// `PWRMGR_AON_BASE_ADDR + PWRMGR_AON_SIZE_BYTES`.
pub const PWRMGR_AON_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rstmgr_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RSTMGR_AON_BASE_ADDR: usize = 0x40410000;

/// Peripheral size for rstmgr_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RSTMGR_AON_BASE_ADDR and
/// `RSTMGR_AON_BASE_ADDR + RSTMGR_AON_SIZE_BYTES`.
pub const RSTMGR_AON_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for clkmgr_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CLKMGR_AON_BASE_ADDR: usize = 0x40420000;

/// Peripheral size for clkmgr_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CLKMGR_AON_BASE_ADDR and
/// `CLKMGR_AON_BASE_ADDR + CLKMGR_AON_SIZE_BYTES`.
pub const CLKMGR_AON_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for sysrst_ctrl_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SYSRST_CTRL_AON_BASE_ADDR: usize = 0x40430000;

/// Peripheral size for sysrst_ctrl_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SYSRST_CTRL_AON_BASE_ADDR and
/// `SYSRST_CTRL_AON_BASE_ADDR + SYSRST_CTRL_AON_SIZE_BYTES`.
pub const SYSRST_CTRL_AON_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for adc_ctrl_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ADC_CTRL_AON_BASE_ADDR: usize = 0x40440000;

/// Peripheral size for adc_ctrl_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ADC_CTRL_AON_BASE_ADDR and
/// `ADC_CTRL_AON_BASE_ADDR + ADC_CTRL_AON_SIZE_BYTES`.
pub const ADC_CTRL_AON_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for pwm_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PWM_AON_BASE_ADDR: usize = 0x40450000;

/// Peripheral size for pwm_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PWM_AON_BASE_ADDR and
/// `PWM_AON_BASE_ADDR + PWM_AON_SIZE_BYTES`.
pub const PWM_AON_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for pinmux_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PINMUX_AON_BASE_ADDR: usize = 0x40460000;

/// Peripheral size for pinmux_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PINMUX_AON_BASE_ADDR and
/// `PINMUX_AON_BASE_ADDR + PINMUX_AON_SIZE_BYTES`.
pub const PINMUX_AON_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for aon_timer_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AON_TIMER_AON_BASE_ADDR: usize = 0x40470000;

/// Peripheral size for aon_timer_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AON_TIMER_AON_BASE_ADDR and
/// `AON_TIMER_AON_BASE_ADDR + AON_TIMER_AON_SIZE_BYTES`.
pub const AON_TIMER_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for ast in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AST_BASE_ADDR: usize = 0x40480000;

/// Peripheral size for ast in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AST_BASE_ADDR and
/// `AST_BASE_ADDR + AST_SIZE_BYTES`.
pub const AST_SIZE_BYTES: usize = 0x400;

/// Peripheral base address for sensor_ctrl_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SENSOR_CTRL_AON_BASE_ADDR: usize = 0x40490000;

/// Peripheral size for sensor_ctrl_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SENSOR_CTRL_AON_BASE_ADDR and
/// `SENSOR_CTRL_AON_BASE_ADDR + SENSOR_CTRL_AON_SIZE_BYTES`.
pub const SENSOR_CTRL_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for regs device on sram_ctrl_ret_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_AON_REGS_BASE_ADDR: usize = 0x40500000;

/// Peripheral size for regs device on sram_ctrl_ret_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_AON_REGS_BASE_ADDR and
/// `SRAM_CTRL_RET_AON_REGS_BASE_ADDR + SRAM_CTRL_RET_AON_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_RET_AON_REGS_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for ram device on sram_ctrl_ret_aon in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_AON_RAM_BASE_ADDR: usize = 0x40600000;

/// Peripheral size for ram device on sram_ctrl_ret_aon in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_AON_RAM_BASE_ADDR and
/// `SRAM_CTRL_RET_AON_RAM_BASE_ADDR + SRAM_CTRL_RET_AON_RAM_SIZE_BYTES`.
pub const SRAM_CTRL_RET_AON_RAM_SIZE_BYTES: usize = 0x100000;

/// Peripheral base address for core device on flash_ctrl in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const FLASH_CTRL_CORE_BASE_ADDR: usize = 0x41000000;

/// Peripheral size for core device on flash_ctrl in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #FLASH_CTRL_CORE_BASE_ADDR and
/// `FLASH_CTRL_CORE_BASE_ADDR + FLASH_CTRL_CORE_SIZE_BYTES`.
pub const FLASH_CTRL_CORE_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for prim device on flash_ctrl in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const FLASH_CTRL_PRIM_BASE_ADDR: usize = 0x41008000;

/// Peripheral size for prim device on flash_ctrl in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #FLASH_CTRL_PRIM_BASE_ADDR and
/// `FLASH_CTRL_PRIM_BASE_ADDR + FLASH_CTRL_PRIM_SIZE_BYTES`.
pub const FLASH_CTRL_PRIM_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for mem device on flash_ctrl in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const FLASH_CTRL_MEM_BASE_ADDR: usize = 0x20000000;

/// Peripheral size for mem device on flash_ctrl in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #FLASH_CTRL_MEM_BASE_ADDR and
/// `FLASH_CTRL_MEM_BASE_ADDR + FLASH_CTRL_MEM_SIZE_BYTES`.
pub const FLASH_CTRL_MEM_SIZE_BYTES: usize = 0x100000;

/// Peripheral base address for regs device on rv_dm in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_REGS_BASE_ADDR: usize = 0x41200000;

/// Peripheral size for regs device on rv_dm in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_REGS_BASE_ADDR and
/// `RV_DM_REGS_BASE_ADDR + RV_DM_REGS_SIZE_BYTES`.
pub const RV_DM_REGS_SIZE_BYTES: usize = 0x4;

/// Peripheral base address for mem device on rv_dm in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_MEM_BASE_ADDR: usize = 0x10000;

/// Peripheral size for mem device on rv_dm in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_MEM_BASE_ADDR and
/// `RV_DM_MEM_BASE_ADDR + RV_DM_MEM_SIZE_BYTES`.
pub const RV_DM_MEM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for rv_plic in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_PLIC_BASE_ADDR: usize = 0x48000000;

/// Peripheral size for rv_plic in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_PLIC_BASE_ADDR and
/// `RV_PLIC_BASE_ADDR + RV_PLIC_SIZE_BYTES`.
pub const RV_PLIC_SIZE_BYTES: usize = 0x8000000;

/// Peripheral base address for regs device on sram_ctrl_main in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_REGS_BASE_ADDR: usize = 0x411C0000;

/// Peripheral size for regs device on sram_ctrl_main in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_REGS_BASE_ADDR and
/// `SRAM_CTRL_MAIN_REGS_BASE_ADDR + SRAM_CTRL_MAIN_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_REGS_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for ram device on sram_ctrl_main in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_RAM_BASE_ADDR: usize = 0x10000000;

/// Peripheral size for ram device on sram_ctrl_main in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_RAM_BASE_ADDR and
/// `SRAM_CTRL_MAIN_RAM_BASE_ADDR + SRAM_CTRL_MAIN_RAM_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_RAM_SIZE_BYTES: usize = 0x20000;

/// Peripheral base address for regs device on rom_ctrl in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL_REGS_BASE_ADDR: usize = 0x411E0000;

/// Peripheral size for regs device on rom_ctrl in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL_REGS_BASE_ADDR and
/// `ROM_CTRL_REGS_BASE_ADDR + ROM_CTRL_REGS_SIZE_BYTES`.
pub const ROM_CTRL_REGS_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rom device on rom_ctrl in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL_ROM_BASE_ADDR: usize = 0x8000;

/// Peripheral size for rom device on rom_ctrl in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL_ROM_BASE_ADDR and
/// `ROM_CTRL_ROM_BASE_ADDR + ROM_CTRL_ROM_SIZE_BYTES`.
pub const ROM_CTRL_ROM_SIZE_BYTES: usize = 0x8000;

/// Peripheral base address for cfg device on rv_core_ibex in top earlgrey.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_CORE_IBEX_CFG_BASE_ADDR: usize = 0x411F0000;

/// Peripheral size for cfg device on rv_core_ibex in top earlgrey.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_CORE_IBEX_CFG_BASE_ADDR and
/// `RV_CORE_IBEX_CFG_BASE_ADDR + RV_CORE_IBEX_CFG_SIZE_BYTES`.
pub const RV_CORE_IBEX_CFG_SIZE_BYTES: usize = 0x100;

/// Memory base address for ram_ret_aon in top earlgrey.
pub const RAM_RET_AON_BASE_ADDR: usize = 0x40600000;

/// Memory size for ram_ret_aon in top earlgrey.
pub const RAM_RET_AON_SIZE_BYTES: usize = 0x100000;

/// Memory base address for eflash in top earlgrey.
pub const EFLASH_BASE_ADDR: usize = 0x20000000;

/// Memory size for eflash in top earlgrey.
pub const EFLASH_SIZE_BYTES: usize = 0x100000;

/// Memory base address for ram_main in top earlgrey.
pub const RAM_MAIN_BASE_ADDR: usize = 0x10000000;

/// Memory size for ram_main in top earlgrey.
pub const RAM_MAIN_SIZE_BYTES: usize = 0x20000;

/// Memory base address for rom in top earlgrey.
pub const ROM_BASE_ADDR: usize = 0x8000;

/// Memory size for rom in top earlgrey.
pub const ROM_SIZE_BYTES: usize = 0x8000;

/// PLIC Interrupt Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// interrupt.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPeripheral {
    /// Unknown Peripheral
    Unknown = 0,
    /// data_proc
    DataProc = 1,
    /// uart0
    Uart0 = 2,
    /// gpio
    Gpio = 3,
    /// spi_device
    SpiDevice = 4,
    /// i2c0
    I2c0 = 5,
    /// pattgen
    Pattgen = 6,
    /// rv_timer
    RvTimer = 7,
    /// otp_ctrl
    OtpCtrl = 8,
    /// alert_handler
    AlertHandler = 9,
    /// spi_host0
    SpiHost0 = 10,
    /// pwrmgr_aon
    PwrmgrAon = 11,
    /// sysrst_ctrl_aon
    SysrstCtrlAon = 12,
    /// adc_ctrl_aon
    AdcCtrlAon = 13,
    /// aon_timer_aon
    AonTimerAon = 14,
    /// sensor_ctrl_aon
    SensorCtrlAon = 15,
    /// flash_ctrl
    FlashCtrl = 16,
}

impl TryFrom<u32> for PlicPeripheral {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::DataProc),
            2 => Ok(Self::Uart0),
            3 => Ok(Self::Gpio),
            4 => Ok(Self::SpiDevice),
            5 => Ok(Self::I2c0),
            6 => Ok(Self::Pattgen),
            7 => Ok(Self::RvTimer),
            8 => Ok(Self::OtpCtrl),
            9 => Ok(Self::AlertHandler),
            10 => Ok(Self::SpiHost0),
            11 => Ok(Self::PwrmgrAon),
            12 => Ok(Self::SysrstCtrlAon),
            13 => Ok(Self::AdcCtrlAon),
            14 => Ok(Self::AonTimerAon),
            15 => Ok(Self::SensorCtrlAon),
            16 => Ok(Self::FlashCtrl),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Source.
///
/// Enumeration of all PLIC interrupt sources. The interrupt sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicIrqId {
    /// No Interrupt
    None = 0,
    /// data_proc_tx_watermark
    DataProcTxWatermark = 1,
    /// data_proc_rx_watermark
    DataProcRxWatermark = 2,
    /// data_proc_tx_empty
    DataProcTxEmpty = 3,
    /// data_proc_rx_overflow
    DataProcRxOverflow = 4,
    /// data_proc_rx_frame_err
    DataProcRxFrameErr = 5,
    /// data_proc_rx_break_err
    DataProcRxBreakErr = 6,
    /// data_proc_rx_timeout
    DataProcRxTimeout = 7,
    /// data_proc_rx_parity_err
    DataProcRxParityErr = 8,
    /// uart0_tx_watermark
    Uart0TxWatermark = 9,
    /// uart0_rx_watermark
    Uart0RxWatermark = 10,
    /// uart0_tx_empty
    Uart0TxEmpty = 11,
    /// uart0_rx_overflow
    Uart0RxOverflow = 12,
    /// uart0_rx_frame_err
    Uart0RxFrameErr = 13,
    /// uart0_rx_break_err
    Uart0RxBreakErr = 14,
    /// uart0_rx_timeout
    Uart0RxTimeout = 15,
    /// uart0_rx_parity_err
    Uart0RxParityErr = 16,
    /// gpio_gpio 0
    GpioGpio0 = 17,
    /// gpio_gpio 1
    GpioGpio1 = 18,
    /// gpio_gpio 2
    GpioGpio2 = 19,
    /// gpio_gpio 3
    GpioGpio3 = 20,
    /// gpio_gpio 4
    GpioGpio4 = 21,
    /// gpio_gpio 5
    GpioGpio5 = 22,
    /// gpio_gpio 6
    GpioGpio6 = 23,
    /// gpio_gpio 7
    GpioGpio7 = 24,
    /// gpio_gpio 8
    GpioGpio8 = 25,
    /// gpio_gpio 9
    GpioGpio9 = 26,
    /// gpio_gpio 10
    GpioGpio10 = 27,
    /// gpio_gpio 11
    GpioGpio11 = 28,
    /// gpio_gpio 12
    GpioGpio12 = 29,
    /// gpio_gpio 13
    GpioGpio13 = 30,
    /// gpio_gpio 14
    GpioGpio14 = 31,
    /// gpio_gpio 15
    GpioGpio15 = 32,
    /// gpio_gpio 16
    GpioGpio16 = 33,
    /// gpio_gpio 17
    GpioGpio17 = 34,
    /// gpio_gpio 18
    GpioGpio18 = 35,
    /// gpio_gpio 19
    GpioGpio19 = 36,
    /// gpio_gpio 20
    GpioGpio20 = 37,
    /// gpio_gpio 21
    GpioGpio21 = 38,
    /// gpio_gpio 22
    GpioGpio22 = 39,
    /// gpio_gpio 23
    GpioGpio23 = 40,
    /// gpio_gpio 24
    GpioGpio24 = 41,
    /// gpio_gpio 25
    GpioGpio25 = 42,
    /// gpio_gpio 26
    GpioGpio26 = 43,
    /// gpio_gpio 27
    GpioGpio27 = 44,
    /// gpio_gpio 28
    GpioGpio28 = 45,
    /// gpio_gpio 29
    GpioGpio29 = 46,
    /// gpio_gpio 30
    GpioGpio30 = 47,
    /// gpio_gpio 31
    GpioGpio31 = 48,
    /// spi_device_generic_rx_full
    SpiDeviceGenericRxFull = 49,
    /// spi_device_generic_rx_watermark
    SpiDeviceGenericRxWatermark = 50,
    /// spi_device_generic_tx_watermark
    SpiDeviceGenericTxWatermark = 51,
    /// spi_device_generic_rx_error
    SpiDeviceGenericRxError = 52,
    /// spi_device_generic_rx_overflow
    SpiDeviceGenericRxOverflow = 53,
    /// spi_device_generic_tx_underflow
    SpiDeviceGenericTxUnderflow = 54,
    /// spi_device_upload_cmdfifo_not_empty
    SpiDeviceUploadCmdfifoNotEmpty = 55,
    /// spi_device_upload_payload_not_empty
    SpiDeviceUploadPayloadNotEmpty = 56,
    /// spi_device_upload_payload_overflow
    SpiDeviceUploadPayloadOverflow = 57,
    /// spi_device_readbuf_watermark
    SpiDeviceReadbufWatermark = 58,
    /// spi_device_readbuf_flip
    SpiDeviceReadbufFlip = 59,
    /// spi_device_tpm_header_not_empty
    SpiDeviceTpmHeaderNotEmpty = 60,
    /// i2c0_fmt_threshold
    I2c0FmtThreshold = 61,
    /// i2c0_rx_threshold
    I2c0RxThreshold = 62,
    /// i2c0_fmt_overflow
    I2c0FmtOverflow = 63,
    /// i2c0_rx_overflow
    I2c0RxOverflow = 64,
    /// i2c0_nak
    I2c0Nak = 65,
    /// i2c0_scl_interference
    I2c0SclInterference = 66,
    /// i2c0_sda_interference
    I2c0SdaInterference = 67,
    /// i2c0_stretch_timeout
    I2c0StretchTimeout = 68,
    /// i2c0_sda_unstable
    I2c0SdaUnstable = 69,
    /// i2c0_cmd_complete
    I2c0CmdComplete = 70,
    /// i2c0_tx_stretch
    I2c0TxStretch = 71,
    /// i2c0_tx_overflow
    I2c0TxOverflow = 72,
    /// i2c0_acq_full
    I2c0AcqFull = 73,
    /// i2c0_unexp_stop
    I2c0UnexpStop = 74,
    /// i2c0_host_timeout
    I2c0HostTimeout = 75,
    /// pattgen_done_ch0
    PattgenDoneCh0 = 76,
    /// pattgen_done_ch1
    PattgenDoneCh1 = 77,
    /// rv_timer_timer_expired_hart0_timer0
    RvTimerTimerExpiredHart0Timer0 = 78,
    /// otp_ctrl_otp_operation_done
    OtpCtrlOtpOperationDone = 79,
    /// otp_ctrl_otp_error
    OtpCtrlOtpError = 80,
    /// alert_handler_classa
    AlertHandlerClassa = 81,
    /// alert_handler_classb
    AlertHandlerClassb = 82,
    /// alert_handler_classc
    AlertHandlerClassc = 83,
    /// alert_handler_classd
    AlertHandlerClassd = 84,
    /// spi_host0_error
    SpiHost0Error = 85,
    /// spi_host0_spi_event
    SpiHost0SpiEvent = 86,
    /// pwrmgr_aon_wakeup
    PwrmgrAonWakeup = 87,
    /// sysrst_ctrl_aon_event_detected
    SysrstCtrlAonEventDetected = 88,
    /// adc_ctrl_aon_match_done
    AdcCtrlAonMatchDone = 89,
    /// aon_timer_aon_wkup_timer_expired
    AonTimerAonWkupTimerExpired = 90,
    /// aon_timer_aon_wdog_timer_bark
    AonTimerAonWdogTimerBark = 91,
    /// sensor_ctrl_aon_io_status_change
    SensorCtrlAonIoStatusChange = 92,
    /// sensor_ctrl_aon_init_status_change
    SensorCtrlAonInitStatusChange = 93,
    /// flash_ctrl_prog_empty
    FlashCtrlProgEmpty = 94,
    /// flash_ctrl_prog_lvl
    FlashCtrlProgLvl = 95,
    /// flash_ctrl_rd_full
    FlashCtrlRdFull = 96,
    /// flash_ctrl_rd_lvl
    FlashCtrlRdLvl = 97,
    /// flash_ctrl_op_done
    FlashCtrlOpDone = 98,
    /// flash_ctrl_corr_err
    FlashCtrlCorrErr = 99,
}

impl TryFrom<u32> for PlicIrqId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::None),
            1 => Ok(Self::DataProcTxWatermark),
            2 => Ok(Self::DataProcRxWatermark),
            3 => Ok(Self::DataProcTxEmpty),
            4 => Ok(Self::DataProcRxOverflow),
            5 => Ok(Self::DataProcRxFrameErr),
            6 => Ok(Self::DataProcRxBreakErr),
            7 => Ok(Self::DataProcRxTimeout),
            8 => Ok(Self::DataProcRxParityErr),
            9 => Ok(Self::Uart0TxWatermark),
            10 => Ok(Self::Uart0RxWatermark),
            11 => Ok(Self::Uart0TxEmpty),
            12 => Ok(Self::Uart0RxOverflow),
            13 => Ok(Self::Uart0RxFrameErr),
            14 => Ok(Self::Uart0RxBreakErr),
            15 => Ok(Self::Uart0RxTimeout),
            16 => Ok(Self::Uart0RxParityErr),
            17 => Ok(Self::GpioGpio0),
            18 => Ok(Self::GpioGpio1),
            19 => Ok(Self::GpioGpio2),
            20 => Ok(Self::GpioGpio3),
            21 => Ok(Self::GpioGpio4),
            22 => Ok(Self::GpioGpio5),
            23 => Ok(Self::GpioGpio6),
            24 => Ok(Self::GpioGpio7),
            25 => Ok(Self::GpioGpio8),
            26 => Ok(Self::GpioGpio9),
            27 => Ok(Self::GpioGpio10),
            28 => Ok(Self::GpioGpio11),
            29 => Ok(Self::GpioGpio12),
            30 => Ok(Self::GpioGpio13),
            31 => Ok(Self::GpioGpio14),
            32 => Ok(Self::GpioGpio15),
            33 => Ok(Self::GpioGpio16),
            34 => Ok(Self::GpioGpio17),
            35 => Ok(Self::GpioGpio18),
            36 => Ok(Self::GpioGpio19),
            37 => Ok(Self::GpioGpio20),
            38 => Ok(Self::GpioGpio21),
            39 => Ok(Self::GpioGpio22),
            40 => Ok(Self::GpioGpio23),
            41 => Ok(Self::GpioGpio24),
            42 => Ok(Self::GpioGpio25),
            43 => Ok(Self::GpioGpio26),
            44 => Ok(Self::GpioGpio27),
            45 => Ok(Self::GpioGpio28),
            46 => Ok(Self::GpioGpio29),
            47 => Ok(Self::GpioGpio30),
            48 => Ok(Self::GpioGpio31),
            49 => Ok(Self::SpiDeviceGenericRxFull),
            50 => Ok(Self::SpiDeviceGenericRxWatermark),
            51 => Ok(Self::SpiDeviceGenericTxWatermark),
            52 => Ok(Self::SpiDeviceGenericRxError),
            53 => Ok(Self::SpiDeviceGenericRxOverflow),
            54 => Ok(Self::SpiDeviceGenericTxUnderflow),
            55 => Ok(Self::SpiDeviceUploadCmdfifoNotEmpty),
            56 => Ok(Self::SpiDeviceUploadPayloadNotEmpty),
            57 => Ok(Self::SpiDeviceUploadPayloadOverflow),
            58 => Ok(Self::SpiDeviceReadbufWatermark),
            59 => Ok(Self::SpiDeviceReadbufFlip),
            60 => Ok(Self::SpiDeviceTpmHeaderNotEmpty),
            61 => Ok(Self::I2c0FmtThreshold),
            62 => Ok(Self::I2c0RxThreshold),
            63 => Ok(Self::I2c0FmtOverflow),
            64 => Ok(Self::I2c0RxOverflow),
            65 => Ok(Self::I2c0Nak),
            66 => Ok(Self::I2c0SclInterference),
            67 => Ok(Self::I2c0SdaInterference),
            68 => Ok(Self::I2c0StretchTimeout),
            69 => Ok(Self::I2c0SdaUnstable),
            70 => Ok(Self::I2c0CmdComplete),
            71 => Ok(Self::I2c0TxStretch),
            72 => Ok(Self::I2c0TxOverflow),
            73 => Ok(Self::I2c0AcqFull),
            74 => Ok(Self::I2c0UnexpStop),
            75 => Ok(Self::I2c0HostTimeout),
            76 => Ok(Self::PattgenDoneCh0),
            77 => Ok(Self::PattgenDoneCh1),
            78 => Ok(Self::RvTimerTimerExpiredHart0Timer0),
            79 => Ok(Self::OtpCtrlOtpOperationDone),
            80 => Ok(Self::OtpCtrlOtpError),
            81 => Ok(Self::AlertHandlerClassa),
            82 => Ok(Self::AlertHandlerClassb),
            83 => Ok(Self::AlertHandlerClassc),
            84 => Ok(Self::AlertHandlerClassd),
            85 => Ok(Self::SpiHost0Error),
            86 => Ok(Self::SpiHost0SpiEvent),
            87 => Ok(Self::PwrmgrAonWakeup),
            88 => Ok(Self::SysrstCtrlAonEventDetected),
            89 => Ok(Self::AdcCtrlAonMatchDone),
            90 => Ok(Self::AonTimerAonWkupTimerExpired),
            91 => Ok(Self::AonTimerAonWdogTimerBark),
            92 => Ok(Self::SensorCtrlAonIoStatusChange),
            93 => Ok(Self::SensorCtrlAonInitStatusChange),
            94 => Ok(Self::FlashCtrlProgEmpty),
            95 => Ok(Self::FlashCtrlProgLvl),
            96 => Ok(Self::FlashCtrlRdFull),
            97 => Ok(Self::FlashCtrlRdLvl),
            98 => Ok(Self::FlashCtrlOpDone),
            99 => Ok(Self::FlashCtrlCorrErr),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Target.
///
/// Enumeration used to determine which set of IE, CC, threshold registers to
/// access for a given interrupt target.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicTarget {
    /// Ibex Core 0
    Ibex0 = 0,
}

/// Alert Handler Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// alert.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertPeripheral {
    /// data_proc
    DataProc = 0,
    /// uart0
    Uart0 = 1,
    /// gpio
    Gpio = 2,
    /// spi_device
    SpiDevice = 3,
    /// i2c0
    I2c0 = 4,
    /// pattgen
    Pattgen = 5,
    /// rv_timer
    RvTimer = 6,
    /// otp_ctrl
    OtpCtrl = 7,
    /// lc_ctrl
    LcCtrl = 8,
    /// spi_host0
    SpiHost0 = 9,
    /// pwrmgr_aon
    PwrmgrAon = 10,
    /// rstmgr_aon
    RstmgrAon = 11,
    /// clkmgr_aon
    ClkmgrAon = 12,
    /// sysrst_ctrl_aon
    SysrstCtrlAon = 13,
    /// adc_ctrl_aon
    AdcCtrlAon = 14,
    /// pwm_aon
    PwmAon = 15,
    /// pinmux_aon
    PinmuxAon = 16,
    /// aon_timer_aon
    AonTimerAon = 17,
    /// sensor_ctrl_aon
    SensorCtrlAon = 18,
    /// sram_ctrl_ret_aon
    SramCtrlRetAon = 19,
    /// flash_ctrl
    FlashCtrl = 20,
    /// rv_dm
    RvDm = 21,
    /// rv_plic
    RvPlic = 22,
    /// sram_ctrl_main
    SramCtrlMain = 23,
    /// rom_ctrl
    RomCtrl = 24,
    /// rv_core_ibex
    RvCoreIbex = 25,
}

/// Alert Handler Alert Source.
///
/// Enumeration of all Alert Handler Alert Sources. The alert sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertId {
    /// data_proc_fatal_fault
    DataProcFatalFault = 0,
    /// uart0_fatal_fault
    Uart0FatalFault = 1,
    /// gpio_fatal_fault
    GpioFatalFault = 2,
    /// spi_device_fatal_fault
    SpiDeviceFatalFault = 3,
    /// i2c0_fatal_fault
    I2c0FatalFault = 4,
    /// pattgen_fatal_fault
    PattgenFatalFault = 5,
    /// rv_timer_fatal_fault
    RvTimerFatalFault = 6,
    /// otp_ctrl_fatal_macro_error
    OtpCtrlFatalMacroError = 7,
    /// otp_ctrl_fatal_check_error
    OtpCtrlFatalCheckError = 8,
    /// otp_ctrl_fatal_bus_integ_error
    OtpCtrlFatalBusIntegError = 9,
    /// otp_ctrl_fatal_prim_otp_alert
    OtpCtrlFatalPrimOtpAlert = 10,
    /// otp_ctrl_recov_prim_otp_alert
    OtpCtrlRecovPrimOtpAlert = 11,
    /// lc_ctrl_fatal_prog_error
    LcCtrlFatalProgError = 12,
    /// lc_ctrl_fatal_state_error
    LcCtrlFatalStateError = 13,
    /// lc_ctrl_fatal_bus_integ_error
    LcCtrlFatalBusIntegError = 14,
    /// spi_host0_fatal_fault
    SpiHost0FatalFault = 15,
    /// pwrmgr_aon_fatal_fault
    PwrmgrAonFatalFault = 16,
    /// rstmgr_aon_fatal_fault
    RstmgrAonFatalFault = 17,
    /// rstmgr_aon_fatal_cnsty_fault
    RstmgrAonFatalCnstyFault = 18,
    /// clkmgr_aon_recov_fault
    ClkmgrAonRecovFault = 19,
    /// clkmgr_aon_fatal_fault
    ClkmgrAonFatalFault = 20,
    /// sysrst_ctrl_aon_fatal_fault
    SysrstCtrlAonFatalFault = 21,
    /// adc_ctrl_aon_fatal_fault
    AdcCtrlAonFatalFault = 22,
    /// pwm_aon_fatal_fault
    PwmAonFatalFault = 23,
    /// pinmux_aon_fatal_fault
    PinmuxAonFatalFault = 24,
    /// aon_timer_aon_fatal_fault
    AonTimerAonFatalFault = 25,
    /// sensor_ctrl_aon_recov_alert
    SensorCtrlAonRecovAlert = 26,
    /// sensor_ctrl_aon_fatal_alert
    SensorCtrlAonFatalAlert = 27,
    /// sram_ctrl_ret_aon_fatal_error
    SramCtrlRetAonFatalError = 28,
    /// flash_ctrl_recov_err
    FlashCtrlRecovErr = 29,
    /// flash_ctrl_fatal_std_err
    FlashCtrlFatalStdErr = 30,
    /// flash_ctrl_fatal_err
    FlashCtrlFatalErr = 31,
    /// flash_ctrl_fatal_prim_flash_alert
    FlashCtrlFatalPrimFlashAlert = 32,
    /// flash_ctrl_recov_prim_flash_alert
    FlashCtrlRecovPrimFlashAlert = 33,
    /// rv_dm_fatal_fault
    RvDmFatalFault = 34,
    /// rv_plic_fatal_fault
    RvPlicFatalFault = 35,
    /// sram_ctrl_main_fatal_error
    SramCtrlMainFatalError = 36,
    /// rom_ctrl_fatal
    RomCtrlFatal = 37,
    /// rv_core_ibex_fatal_sw_err
    RvCoreIbexFatalSwErr = 38,
    /// rv_core_ibex_recov_sw_err
    RvCoreIbexRecovSwErr = 39,
    /// rv_core_ibex_fatal_hw_err
    RvCoreIbexFatalHwErr = 40,
    /// rv_core_ibex_recov_hw_err
    RvCoreIbexRecovHwErr = 41,
}

impl TryFrom<u32> for AlertId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::DataProcFatalFault),
            1 => Ok(Self::Uart0FatalFault),
            2 => Ok(Self::GpioFatalFault),
            3 => Ok(Self::SpiDeviceFatalFault),
            4 => Ok(Self::I2c0FatalFault),
            5 => Ok(Self::PattgenFatalFault),
            6 => Ok(Self::RvTimerFatalFault),
            7 => Ok(Self::OtpCtrlFatalMacroError),
            8 => Ok(Self::OtpCtrlFatalCheckError),
            9 => Ok(Self::OtpCtrlFatalBusIntegError),
            10 => Ok(Self::OtpCtrlFatalPrimOtpAlert),
            11 => Ok(Self::OtpCtrlRecovPrimOtpAlert),
            12 => Ok(Self::LcCtrlFatalProgError),
            13 => Ok(Self::LcCtrlFatalStateError),
            14 => Ok(Self::LcCtrlFatalBusIntegError),
            15 => Ok(Self::SpiHost0FatalFault),
            16 => Ok(Self::PwrmgrAonFatalFault),
            17 => Ok(Self::RstmgrAonFatalFault),
            18 => Ok(Self::RstmgrAonFatalCnstyFault),
            19 => Ok(Self::ClkmgrAonRecovFault),
            20 => Ok(Self::ClkmgrAonFatalFault),
            21 => Ok(Self::SysrstCtrlAonFatalFault),
            22 => Ok(Self::AdcCtrlAonFatalFault),
            23 => Ok(Self::PwmAonFatalFault),
            24 => Ok(Self::PinmuxAonFatalFault),
            25 => Ok(Self::AonTimerAonFatalFault),
            26 => Ok(Self::SensorCtrlAonRecovAlert),
            27 => Ok(Self::SensorCtrlAonFatalAlert),
            28 => Ok(Self::SramCtrlRetAonFatalError),
            29 => Ok(Self::FlashCtrlRecovErr),
            30 => Ok(Self::FlashCtrlFatalStdErr),
            31 => Ok(Self::FlashCtrlFatalErr),
            32 => Ok(Self::FlashCtrlFatalPrimFlashAlert),
            33 => Ok(Self::FlashCtrlRecovPrimFlashAlert),
            34 => Ok(Self::RvDmFatalFault),
            35 => Ok(Self::RvPlicFatalFault),
            36 => Ok(Self::SramCtrlMainFatalError),
            37 => Ok(Self::RomCtrlFatal),
            38 => Ok(Self::RvCoreIbexFatalSwErr),
            39 => Ok(Self::RvCoreIbexRecovSwErr),
            40 => Ok(Self::RvCoreIbexFatalHwErr),
            41 => Ok(Self::RvCoreIbexRecovHwErr),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Source to Peripheral Map
///
/// This array is a mapping from `PlicIrqId` to
/// `PlicPeripheral`.
pub const PLIC_INTERRUPT_FOR_PERIPHERAL: [PlicPeripheral; 100] = [
    // None -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // DataProcTxWatermark -> PlicPeripheral::DataProc
    PlicPeripheral::DataProc,
    // DataProcRxWatermark -> PlicPeripheral::DataProc
    PlicPeripheral::DataProc,
    // DataProcTxEmpty -> PlicPeripheral::DataProc
    PlicPeripheral::DataProc,
    // DataProcRxOverflow -> PlicPeripheral::DataProc
    PlicPeripheral::DataProc,
    // DataProcRxFrameErr -> PlicPeripheral::DataProc
    PlicPeripheral::DataProc,
    // DataProcRxBreakErr -> PlicPeripheral::DataProc
    PlicPeripheral::DataProc,
    // DataProcRxTimeout -> PlicPeripheral::DataProc
    PlicPeripheral::DataProc,
    // DataProcRxParityErr -> PlicPeripheral::DataProc
    PlicPeripheral::DataProc,
    // Uart0TxWatermark -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxWatermark -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0TxEmpty -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxOverflow -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxFrameErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxBreakErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxTimeout -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxParityErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // GpioGpio0 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio1 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio2 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio3 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio4 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio5 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio6 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio7 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio8 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio9 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio10 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio11 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio12 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio13 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio14 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio15 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio16 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio17 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio18 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio19 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio20 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio21 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio22 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio23 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio24 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio25 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio26 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio27 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio28 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio29 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio30 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio31 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // SpiDeviceGenericRxFull -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceGenericRxWatermark -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceGenericTxWatermark -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceGenericRxError -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceGenericRxOverflow -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceGenericTxUnderflow -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceUploadCmdfifoNotEmpty -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceUploadPayloadNotEmpty -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceUploadPayloadOverflow -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceReadbufWatermark -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceReadbufFlip -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // SpiDeviceTpmHeaderNotEmpty -> PlicPeripheral::SpiDevice
    PlicPeripheral::SpiDevice,
    // I2c0FmtThreshold -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0RxThreshold -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0FmtOverflow -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0RxOverflow -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0Nak -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0SclInterference -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0SdaInterference -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0StretchTimeout -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0SdaUnstable -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0CmdComplete -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0TxStretch -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0TxOverflow -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0AcqFull -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0UnexpStop -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // I2c0HostTimeout -> PlicPeripheral::I2c0
    PlicPeripheral::I2c0,
    // PattgenDoneCh0 -> PlicPeripheral::Pattgen
    PlicPeripheral::Pattgen,
    // PattgenDoneCh1 -> PlicPeripheral::Pattgen
    PlicPeripheral::Pattgen,
    // RvTimerTimerExpiredHart0Timer0 -> PlicPeripheral::RvTimer
    PlicPeripheral::RvTimer,
    // OtpCtrlOtpOperationDone -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // OtpCtrlOtpError -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // AlertHandlerClassa -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassb -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassc -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassd -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // SpiHost0Error -> PlicPeripheral::SpiHost0
    PlicPeripheral::SpiHost0,
    // SpiHost0SpiEvent -> PlicPeripheral::SpiHost0
    PlicPeripheral::SpiHost0,
    // PwrmgrAonWakeup -> PlicPeripheral::PwrmgrAon
    PlicPeripheral::PwrmgrAon,
    // SysrstCtrlAonEventDetected -> PlicPeripheral::SysrstCtrlAon
    PlicPeripheral::SysrstCtrlAon,
    // AdcCtrlAonMatchDone -> PlicPeripheral::AdcCtrlAon
    PlicPeripheral::AdcCtrlAon,
    // AonTimerAonWkupTimerExpired -> PlicPeripheral::AonTimerAon
    PlicPeripheral::AonTimerAon,
    // AonTimerAonWdogTimerBark -> PlicPeripheral::AonTimerAon
    PlicPeripheral::AonTimerAon,
    // SensorCtrlAonIoStatusChange -> PlicPeripheral::SensorCtrlAon
    PlicPeripheral::SensorCtrlAon,
    // SensorCtrlAonInitStatusChange -> PlicPeripheral::SensorCtrlAon
    PlicPeripheral::SensorCtrlAon,
    // FlashCtrlProgEmpty -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlProgLvl -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlRdFull -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlRdLvl -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlOpDone -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
    // FlashCtrlCorrErr -> PlicPeripheral::FlashCtrl
    PlicPeripheral::FlashCtrl,
];

/// Alert Handler Alert Source to Peripheral Map
///
/// This array is a mapping from `AlertId` to
/// `AlertPeripheral`.
pub const ALERT_FOR_PERIPHERAL: [AlertPeripheral; 42] = [
    // DataProcFatalFault -> AlertPeripheral::DataProc
    AlertPeripheral::DataProc,
    // Uart0FatalFault -> AlertPeripheral::Uart0
    AlertPeripheral::Uart0,
    // GpioFatalFault -> AlertPeripheral::Gpio
    AlertPeripheral::Gpio,
    // SpiDeviceFatalFault -> AlertPeripheral::SpiDevice
    AlertPeripheral::SpiDevice,
    // I2c0FatalFault -> AlertPeripheral::I2c0
    AlertPeripheral::I2c0,
    // PattgenFatalFault -> AlertPeripheral::Pattgen
    AlertPeripheral::Pattgen,
    // RvTimerFatalFault -> AlertPeripheral::RvTimer
    AlertPeripheral::RvTimer,
    // OtpCtrlFatalMacroError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalCheckError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalBusIntegError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlRecovPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // LcCtrlFatalProgError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalStateError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalBusIntegError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // SpiHost0FatalFault -> AlertPeripheral::SpiHost0
    AlertPeripheral::SpiHost0,
    // PwrmgrAonFatalFault -> AlertPeripheral::PwrmgrAon
    AlertPeripheral::PwrmgrAon,
    // RstmgrAonFatalFault -> AlertPeripheral::RstmgrAon
    AlertPeripheral::RstmgrAon,
    // RstmgrAonFatalCnstyFault -> AlertPeripheral::RstmgrAon
    AlertPeripheral::RstmgrAon,
    // ClkmgrAonRecovFault -> AlertPeripheral::ClkmgrAon
    AlertPeripheral::ClkmgrAon,
    // ClkmgrAonFatalFault -> AlertPeripheral::ClkmgrAon
    AlertPeripheral::ClkmgrAon,
    // SysrstCtrlAonFatalFault -> AlertPeripheral::SysrstCtrlAon
    AlertPeripheral::SysrstCtrlAon,
    // AdcCtrlAonFatalFault -> AlertPeripheral::AdcCtrlAon
    AlertPeripheral::AdcCtrlAon,
    // PwmAonFatalFault -> AlertPeripheral::PwmAon
    AlertPeripheral::PwmAon,
    // PinmuxAonFatalFault -> AlertPeripheral::PinmuxAon
    AlertPeripheral::PinmuxAon,
    // AonTimerAonFatalFault -> AlertPeripheral::AonTimerAon
    AlertPeripheral::AonTimerAon,
    // SensorCtrlAonRecovAlert -> AlertPeripheral::SensorCtrlAon
    AlertPeripheral::SensorCtrlAon,
    // SensorCtrlAonFatalAlert -> AlertPeripheral::SensorCtrlAon
    AlertPeripheral::SensorCtrlAon,
    // SramCtrlRetAonFatalError -> AlertPeripheral::SramCtrlRetAon
    AlertPeripheral::SramCtrlRetAon,
    // FlashCtrlRecovErr -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // FlashCtrlFatalStdErr -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // FlashCtrlFatalErr -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // FlashCtrlFatalPrimFlashAlert -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // FlashCtrlRecovPrimFlashAlert -> AlertPeripheral::FlashCtrl
    AlertPeripheral::FlashCtrl,
    // RvDmFatalFault -> AlertPeripheral::RvDm
    AlertPeripheral::RvDm,
    // RvPlicFatalFault -> AlertPeripheral::RvPlic
    AlertPeripheral::RvPlic,
    // SramCtrlMainFatalError -> AlertPeripheral::SramCtrlMain
    AlertPeripheral::SramCtrlMain,
    // RomCtrlFatal -> AlertPeripheral::RomCtrl
    AlertPeripheral::RomCtrl,
    // RvCoreIbexFatalSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexFatalHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
];

// PERIPH_INSEL ranges from 0 to NUM_MIO_PADS + 2 -1}
//  0 and 1 are tied to value 0 and 1
pub const NUM_MIO_PADS: usize = 47;
pub const NUM_DIO_PADS: usize = 14;

pub const PINMUX_MIO_PERIPH_INSEL_IDX_OFFSET: usize = 2;
pub const PINMUX_PERIPH_OUTSEL_IDX_OFFSET: usize = 3;

/// Pinmux Peripheral Input.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxPeripheralIn {
    /// Peripheral Input 0
    GpioGpio0 = 0,
    /// Peripheral Input 1
    GpioGpio1 = 1,
    /// Peripheral Input 2
    GpioGpio2 = 2,
    /// Peripheral Input 3
    GpioGpio3 = 3,
    /// Peripheral Input 4
    GpioGpio4 = 4,
    /// Peripheral Input 5
    GpioGpio5 = 5,
    /// Peripheral Input 6
    GpioGpio6 = 6,
    /// Peripheral Input 7
    GpioGpio7 = 7,
    /// Peripheral Input 8
    GpioGpio8 = 8,
    /// Peripheral Input 9
    GpioGpio9 = 9,
    /// Peripheral Input 10
    GpioGpio10 = 10,
    /// Peripheral Input 11
    GpioGpio11 = 11,
    /// Peripheral Input 12
    GpioGpio12 = 12,
    /// Peripheral Input 13
    GpioGpio13 = 13,
    /// Peripheral Input 14
    GpioGpio14 = 14,
    /// Peripheral Input 15
    GpioGpio15 = 15,
    /// Peripheral Input 16
    GpioGpio16 = 16,
    /// Peripheral Input 17
    GpioGpio17 = 17,
    /// Peripheral Input 18
    GpioGpio18 = 18,
    /// Peripheral Input 19
    GpioGpio19 = 19,
    /// Peripheral Input 20
    GpioGpio20 = 20,
    /// Peripheral Input 21
    GpioGpio21 = 21,
    /// Peripheral Input 22
    GpioGpio22 = 22,
    /// Peripheral Input 23
    GpioGpio23 = 23,
    /// Peripheral Input 24
    GpioGpio24 = 24,
    /// Peripheral Input 25
    GpioGpio25 = 25,
    /// Peripheral Input 26
    GpioGpio26 = 26,
    /// Peripheral Input 27
    GpioGpio27 = 27,
    /// Peripheral Input 28
    GpioGpio28 = 28,
    /// Peripheral Input 29
    GpioGpio29 = 29,
    /// Peripheral Input 30
    GpioGpio30 = 30,
    /// Peripheral Input 31
    GpioGpio31 = 31,
    /// Peripheral Input 32
    I2c0Sda = 32,
    /// Peripheral Input 33
    I2c0Scl = 33,
    /// Peripheral Input 34
    Uart0Rx = 34,
    /// Peripheral Input 35
    SpiDeviceTpmCsb = 35,
    /// Peripheral Input 36
    FlashCtrlTck = 36,
    /// Peripheral Input 37
    FlashCtrlTms = 37,
    /// Peripheral Input 38
    FlashCtrlTdi = 38,
    /// Peripheral Input 39
    SysrstCtrlAonAcPresent = 39,
    /// Peripheral Input 40
    SysrstCtrlAonKey0In = 40,
    /// Peripheral Input 41
    SysrstCtrlAonKey1In = 41,
    /// Peripheral Input 42
    SysrstCtrlAonKey2In = 42,
    /// Peripheral Input 43
    SysrstCtrlAonPwrbIn = 43,
    /// Peripheral Input 44
    SysrstCtrlAonLidOpen = 44,
}

impl TryFrom<u32> for PinmuxPeripheralIn {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::GpioGpio0),
            1 => Ok(Self::GpioGpio1),
            2 => Ok(Self::GpioGpio2),
            3 => Ok(Self::GpioGpio3),
            4 => Ok(Self::GpioGpio4),
            5 => Ok(Self::GpioGpio5),
            6 => Ok(Self::GpioGpio6),
            7 => Ok(Self::GpioGpio7),
            8 => Ok(Self::GpioGpio8),
            9 => Ok(Self::GpioGpio9),
            10 => Ok(Self::GpioGpio10),
            11 => Ok(Self::GpioGpio11),
            12 => Ok(Self::GpioGpio12),
            13 => Ok(Self::GpioGpio13),
            14 => Ok(Self::GpioGpio14),
            15 => Ok(Self::GpioGpio15),
            16 => Ok(Self::GpioGpio16),
            17 => Ok(Self::GpioGpio17),
            18 => Ok(Self::GpioGpio18),
            19 => Ok(Self::GpioGpio19),
            20 => Ok(Self::GpioGpio20),
            21 => Ok(Self::GpioGpio21),
            22 => Ok(Self::GpioGpio22),
            23 => Ok(Self::GpioGpio23),
            24 => Ok(Self::GpioGpio24),
            25 => Ok(Self::GpioGpio25),
            26 => Ok(Self::GpioGpio26),
            27 => Ok(Self::GpioGpio27),
            28 => Ok(Self::GpioGpio28),
            29 => Ok(Self::GpioGpio29),
            30 => Ok(Self::GpioGpio30),
            31 => Ok(Self::GpioGpio31),
            32 => Ok(Self::I2c0Sda),
            33 => Ok(Self::I2c0Scl),
            34 => Ok(Self::Uart0Rx),
            35 => Ok(Self::SpiDeviceTpmCsb),
            36 => Ok(Self::FlashCtrlTck),
            37 => Ok(Self::FlashCtrlTms),
            38 => Ok(Self::FlashCtrlTdi),
            39 => Ok(Self::SysrstCtrlAonAcPresent),
            40 => Ok(Self::SysrstCtrlAonKey0In),
            41 => Ok(Self::SysrstCtrlAonKey1In),
            42 => Ok(Self::SysrstCtrlAonKey2In),
            43 => Ok(Self::SysrstCtrlAonPwrbIn),
            44 => Ok(Self::SysrstCtrlAonLidOpen),
            _ => Err(val),
        }
    }
}

/// Pinmux MIO Input Selector.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxInsel {
    /// Tie constantly to zero
    ConstantZero = 0,
    /// Tie constantly to one
    ConstantOne = 1,
    /// MIO Pad 0
    Ioa0 = 2,
    /// MIO Pad 1
    Ioa1 = 3,
    /// MIO Pad 2
    Ioa2 = 4,
    /// MIO Pad 3
    Ioa3 = 5,
    /// MIO Pad 4
    Ioa4 = 6,
    /// MIO Pad 5
    Ioa5 = 7,
    /// MIO Pad 6
    Ioa6 = 8,
    /// MIO Pad 7
    Ioa7 = 9,
    /// MIO Pad 8
    Ioa8 = 10,
    /// MIO Pad 9
    Iob0 = 11,
    /// MIO Pad 10
    Iob1 = 12,
    /// MIO Pad 11
    Iob2 = 13,
    /// MIO Pad 12
    Iob3 = 14,
    /// MIO Pad 13
    Iob4 = 15,
    /// MIO Pad 14
    Iob5 = 16,
    /// MIO Pad 15
    Iob6 = 17,
    /// MIO Pad 16
    Iob7 = 18,
    /// MIO Pad 17
    Iob8 = 19,
    /// MIO Pad 18
    Iob9 = 20,
    /// MIO Pad 19
    Iob10 = 21,
    /// MIO Pad 20
    Iob11 = 22,
    /// MIO Pad 21
    Iob12 = 23,
    /// MIO Pad 22
    Ioc0 = 24,
    /// MIO Pad 23
    Ioc1 = 25,
    /// MIO Pad 24
    Ioc2 = 26,
    /// MIO Pad 25
    Ioc3 = 27,
    /// MIO Pad 26
    Ioc4 = 28,
    /// MIO Pad 27
    Ioc5 = 29,
    /// MIO Pad 28
    Ioc6 = 30,
    /// MIO Pad 29
    Ioc7 = 31,
    /// MIO Pad 30
    Ioc8 = 32,
    /// MIO Pad 31
    Ioc9 = 33,
    /// MIO Pad 32
    Ioc10 = 34,
    /// MIO Pad 33
    Ioc11 = 35,
    /// MIO Pad 34
    Ioc12 = 36,
    /// MIO Pad 35
    Ior0 = 37,
    /// MIO Pad 36
    Ior1 = 38,
    /// MIO Pad 37
    Ior2 = 39,
    /// MIO Pad 38
    Ior3 = 40,
    /// MIO Pad 39
    Ior4 = 41,
    /// MIO Pad 40
    Ior5 = 42,
    /// MIO Pad 41
    Ior6 = 43,
    /// MIO Pad 42
    Ior7 = 44,
    /// MIO Pad 43
    Ior10 = 45,
    /// MIO Pad 44
    Ior11 = 46,
    /// MIO Pad 45
    Ior12 = 47,
    /// MIO Pad 46
    Ior13 = 48,
}

impl TryFrom<u32> for PinmuxInsel {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::ConstantZero),
            1 => Ok(Self::ConstantOne),
            2 => Ok(Self::Ioa0),
            3 => Ok(Self::Ioa1),
            4 => Ok(Self::Ioa2),
            5 => Ok(Self::Ioa3),
            6 => Ok(Self::Ioa4),
            7 => Ok(Self::Ioa5),
            8 => Ok(Self::Ioa6),
            9 => Ok(Self::Ioa7),
            10 => Ok(Self::Ioa8),
            11 => Ok(Self::Iob0),
            12 => Ok(Self::Iob1),
            13 => Ok(Self::Iob2),
            14 => Ok(Self::Iob3),
            15 => Ok(Self::Iob4),
            16 => Ok(Self::Iob5),
            17 => Ok(Self::Iob6),
            18 => Ok(Self::Iob7),
            19 => Ok(Self::Iob8),
            20 => Ok(Self::Iob9),
            21 => Ok(Self::Iob10),
            22 => Ok(Self::Iob11),
            23 => Ok(Self::Iob12),
            24 => Ok(Self::Ioc0),
            25 => Ok(Self::Ioc1),
            26 => Ok(Self::Ioc2),
            27 => Ok(Self::Ioc3),
            28 => Ok(Self::Ioc4),
            29 => Ok(Self::Ioc5),
            30 => Ok(Self::Ioc6),
            31 => Ok(Self::Ioc7),
            32 => Ok(Self::Ioc8),
            33 => Ok(Self::Ioc9),
            34 => Ok(Self::Ioc10),
            35 => Ok(Self::Ioc11),
            36 => Ok(Self::Ioc12),
            37 => Ok(Self::Ior0),
            38 => Ok(Self::Ior1),
            39 => Ok(Self::Ior2),
            40 => Ok(Self::Ior3),
            41 => Ok(Self::Ior4),
            42 => Ok(Self::Ior5),
            43 => Ok(Self::Ior6),
            44 => Ok(Self::Ior7),
            45 => Ok(Self::Ior10),
            46 => Ok(Self::Ior11),
            47 => Ok(Self::Ior12),
            48 => Ok(Self::Ior13),
            _ => Err(val),
        }
    }
}

/// Pinmux MIO Output.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxMioOut {
    /// MIO Pad 0
    Ioa0 = 0,
    /// MIO Pad 1
    Ioa1 = 1,
    /// MIO Pad 2
    Ioa2 = 2,
    /// MIO Pad 3
    Ioa3 = 3,
    /// MIO Pad 4
    Ioa4 = 4,
    /// MIO Pad 5
    Ioa5 = 5,
    /// MIO Pad 6
    Ioa6 = 6,
    /// MIO Pad 7
    Ioa7 = 7,
    /// MIO Pad 8
    Ioa8 = 8,
    /// MIO Pad 9
    Iob0 = 9,
    /// MIO Pad 10
    Iob1 = 10,
    /// MIO Pad 11
    Iob2 = 11,
    /// MIO Pad 12
    Iob3 = 12,
    /// MIO Pad 13
    Iob4 = 13,
    /// MIO Pad 14
    Iob5 = 14,
    /// MIO Pad 15
    Iob6 = 15,
    /// MIO Pad 16
    Iob7 = 16,
    /// MIO Pad 17
    Iob8 = 17,
    /// MIO Pad 18
    Iob9 = 18,
    /// MIO Pad 19
    Iob10 = 19,
    /// MIO Pad 20
    Iob11 = 20,
    /// MIO Pad 21
    Iob12 = 21,
    /// MIO Pad 22
    Ioc0 = 22,
    /// MIO Pad 23
    Ioc1 = 23,
    /// MIO Pad 24
    Ioc2 = 24,
    /// MIO Pad 25
    Ioc3 = 25,
    /// MIO Pad 26
    Ioc4 = 26,
    /// MIO Pad 27
    Ioc5 = 27,
    /// MIO Pad 28
    Ioc6 = 28,
    /// MIO Pad 29
    Ioc7 = 29,
    /// MIO Pad 30
    Ioc8 = 30,
    /// MIO Pad 31
    Ioc9 = 31,
    /// MIO Pad 32
    Ioc10 = 32,
    /// MIO Pad 33
    Ioc11 = 33,
    /// MIO Pad 34
    Ioc12 = 34,
    /// MIO Pad 35
    Ior0 = 35,
    /// MIO Pad 36
    Ior1 = 36,
    /// MIO Pad 37
    Ior2 = 37,
    /// MIO Pad 38
    Ior3 = 38,
    /// MIO Pad 39
    Ior4 = 39,
    /// MIO Pad 40
    Ior5 = 40,
    /// MIO Pad 41
    Ior6 = 41,
    /// MIO Pad 42
    Ior7 = 42,
    /// MIO Pad 43
    Ior10 = 43,
    /// MIO Pad 44
    Ior11 = 44,
    /// MIO Pad 45
    Ior12 = 45,
    /// MIO Pad 46
    Ior13 = 46,
}

impl TryFrom<u32> for PinmuxMioOut {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Ioa0),
            1 => Ok(Self::Ioa1),
            2 => Ok(Self::Ioa2),
            3 => Ok(Self::Ioa3),
            4 => Ok(Self::Ioa4),
            5 => Ok(Self::Ioa5),
            6 => Ok(Self::Ioa6),
            7 => Ok(Self::Ioa7),
            8 => Ok(Self::Ioa8),
            9 => Ok(Self::Iob0),
            10 => Ok(Self::Iob1),
            11 => Ok(Self::Iob2),
            12 => Ok(Self::Iob3),
            13 => Ok(Self::Iob4),
            14 => Ok(Self::Iob5),
            15 => Ok(Self::Iob6),
            16 => Ok(Self::Iob7),
            17 => Ok(Self::Iob8),
            18 => Ok(Self::Iob9),
            19 => Ok(Self::Iob10),
            20 => Ok(Self::Iob11),
            21 => Ok(Self::Iob12),
            22 => Ok(Self::Ioc0),
            23 => Ok(Self::Ioc1),
            24 => Ok(Self::Ioc2),
            25 => Ok(Self::Ioc3),
            26 => Ok(Self::Ioc4),
            27 => Ok(Self::Ioc5),
            28 => Ok(Self::Ioc6),
            29 => Ok(Self::Ioc7),
            30 => Ok(Self::Ioc8),
            31 => Ok(Self::Ioc9),
            32 => Ok(Self::Ioc10),
            33 => Ok(Self::Ioc11),
            34 => Ok(Self::Ioc12),
            35 => Ok(Self::Ior0),
            36 => Ok(Self::Ior1),
            37 => Ok(Self::Ior2),
            38 => Ok(Self::Ior3),
            39 => Ok(Self::Ior4),
            40 => Ok(Self::Ior5),
            41 => Ok(Self::Ior6),
            42 => Ok(Self::Ior7),
            43 => Ok(Self::Ior10),
            44 => Ok(Self::Ior11),
            45 => Ok(Self::Ior12),
            46 => Ok(Self::Ior13),
            _ => Err(val),
        }
    }
}

/// Pinmux Peripheral Output Selector.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxOutsel {
    /// Tie constantly to zero
    ConstantZero = 0,
    /// Tie constantly to one
    ConstantOne = 1,
    /// Tie constantly to high-Z
    ConstantHighZ = 2,
    /// Peripheral Output 0
    GpioGpio0 = 3,
    /// Peripheral Output 1
    GpioGpio1 = 4,
    /// Peripheral Output 2
    GpioGpio2 = 5,
    /// Peripheral Output 3
    GpioGpio3 = 6,
    /// Peripheral Output 4
    GpioGpio4 = 7,
    /// Peripheral Output 5
    GpioGpio5 = 8,
    /// Peripheral Output 6
    GpioGpio6 = 9,
    /// Peripheral Output 7
    GpioGpio7 = 10,
    /// Peripheral Output 8
    GpioGpio8 = 11,
    /// Peripheral Output 9
    GpioGpio9 = 12,
    /// Peripheral Output 10
    GpioGpio10 = 13,
    /// Peripheral Output 11
    GpioGpio11 = 14,
    /// Peripheral Output 12
    GpioGpio12 = 15,
    /// Peripheral Output 13
    GpioGpio13 = 16,
    /// Peripheral Output 14
    GpioGpio14 = 17,
    /// Peripheral Output 15
    GpioGpio15 = 18,
    /// Peripheral Output 16
    GpioGpio16 = 19,
    /// Peripheral Output 17
    GpioGpio17 = 20,
    /// Peripheral Output 18
    GpioGpio18 = 21,
    /// Peripheral Output 19
    GpioGpio19 = 22,
    /// Peripheral Output 20
    GpioGpio20 = 23,
    /// Peripheral Output 21
    GpioGpio21 = 24,
    /// Peripheral Output 22
    GpioGpio22 = 25,
    /// Peripheral Output 23
    GpioGpio23 = 26,
    /// Peripheral Output 24
    GpioGpio24 = 27,
    /// Peripheral Output 25
    GpioGpio25 = 28,
    /// Peripheral Output 26
    GpioGpio26 = 29,
    /// Peripheral Output 27
    GpioGpio27 = 30,
    /// Peripheral Output 28
    GpioGpio28 = 31,
    /// Peripheral Output 29
    GpioGpio29 = 32,
    /// Peripheral Output 30
    GpioGpio30 = 33,
    /// Peripheral Output 31
    GpioGpio31 = 34,
    /// Peripheral Output 32
    I2c0Sda = 35,
    /// Peripheral Output 33
    I2c0Scl = 36,
    /// Peripheral Output 34
    Uart0Tx = 37,
    /// Peripheral Output 35
    PattgenPda0Tx = 38,
    /// Peripheral Output 36
    PattgenPcl0Tx = 39,
    /// Peripheral Output 37
    PattgenPda1Tx = 40,
    /// Peripheral Output 38
    PattgenPcl1Tx = 41,
    /// Peripheral Output 39
    FlashCtrlTdo = 42,
    /// Peripheral Output 40
    SensorCtrlAonAstDebugOut0 = 43,
    /// Peripheral Output 41
    SensorCtrlAonAstDebugOut1 = 44,
    /// Peripheral Output 42
    SensorCtrlAonAstDebugOut2 = 45,
    /// Peripheral Output 43
    SensorCtrlAonAstDebugOut3 = 46,
    /// Peripheral Output 44
    SensorCtrlAonAstDebugOut4 = 47,
    /// Peripheral Output 45
    SensorCtrlAonAstDebugOut5 = 48,
    /// Peripheral Output 46
    SensorCtrlAonAstDebugOut6 = 49,
    /// Peripheral Output 47
    SensorCtrlAonAstDebugOut7 = 50,
    /// Peripheral Output 48
    SensorCtrlAonAstDebugOut8 = 51,
    /// Peripheral Output 49
    PwmAonPwm0 = 52,
    /// Peripheral Output 50
    PwmAonPwm1 = 53,
    /// Peripheral Output 51
    PwmAonPwm2 = 54,
    /// Peripheral Output 52
    PwmAonPwm3 = 55,
    /// Peripheral Output 53
    PwmAonPwm4 = 56,
    /// Peripheral Output 54
    PwmAonPwm5 = 57,
    /// Peripheral Output 55
    OtpCtrlTest0 = 58,
    /// Peripheral Output 56
    SysrstCtrlAonBatDisable = 59,
    /// Peripheral Output 57
    SysrstCtrlAonKey0Out = 60,
    /// Peripheral Output 58
    SysrstCtrlAonKey1Out = 61,
    /// Peripheral Output 59
    SysrstCtrlAonKey2Out = 62,
    /// Peripheral Output 60
    SysrstCtrlAonPwrbOut = 63,
    /// Peripheral Output 61
    SysrstCtrlAonZ3Wakeup = 64,
}

impl TryFrom<u32> for PinmuxOutsel {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::ConstantZero),
            1 => Ok(Self::ConstantOne),
            2 => Ok(Self::ConstantHighZ),
            3 => Ok(Self::GpioGpio0),
            4 => Ok(Self::GpioGpio1),
            5 => Ok(Self::GpioGpio2),
            6 => Ok(Self::GpioGpio3),
            7 => Ok(Self::GpioGpio4),
            8 => Ok(Self::GpioGpio5),
            9 => Ok(Self::GpioGpio6),
            10 => Ok(Self::GpioGpio7),
            11 => Ok(Self::GpioGpio8),
            12 => Ok(Self::GpioGpio9),
            13 => Ok(Self::GpioGpio10),
            14 => Ok(Self::GpioGpio11),
            15 => Ok(Self::GpioGpio12),
            16 => Ok(Self::GpioGpio13),
            17 => Ok(Self::GpioGpio14),
            18 => Ok(Self::GpioGpio15),
            19 => Ok(Self::GpioGpio16),
            20 => Ok(Self::GpioGpio17),
            21 => Ok(Self::GpioGpio18),
            22 => Ok(Self::GpioGpio19),
            23 => Ok(Self::GpioGpio20),
            24 => Ok(Self::GpioGpio21),
            25 => Ok(Self::GpioGpio22),
            26 => Ok(Self::GpioGpio23),
            27 => Ok(Self::GpioGpio24),
            28 => Ok(Self::GpioGpio25),
            29 => Ok(Self::GpioGpio26),
            30 => Ok(Self::GpioGpio27),
            31 => Ok(Self::GpioGpio28),
            32 => Ok(Self::GpioGpio29),
            33 => Ok(Self::GpioGpio30),
            34 => Ok(Self::GpioGpio31),
            35 => Ok(Self::I2c0Sda),
            36 => Ok(Self::I2c0Scl),
            37 => Ok(Self::Uart0Tx),
            38 => Ok(Self::PattgenPda0Tx),
            39 => Ok(Self::PattgenPcl0Tx),
            40 => Ok(Self::PattgenPda1Tx),
            41 => Ok(Self::PattgenPcl1Tx),
            42 => Ok(Self::FlashCtrlTdo),
            43 => Ok(Self::SensorCtrlAonAstDebugOut0),
            44 => Ok(Self::SensorCtrlAonAstDebugOut1),
            45 => Ok(Self::SensorCtrlAonAstDebugOut2),
            46 => Ok(Self::SensorCtrlAonAstDebugOut3),
            47 => Ok(Self::SensorCtrlAonAstDebugOut4),
            48 => Ok(Self::SensorCtrlAonAstDebugOut5),
            49 => Ok(Self::SensorCtrlAonAstDebugOut6),
            50 => Ok(Self::SensorCtrlAonAstDebugOut7),
            51 => Ok(Self::SensorCtrlAonAstDebugOut8),
            52 => Ok(Self::PwmAonPwm0),
            53 => Ok(Self::PwmAonPwm1),
            54 => Ok(Self::PwmAonPwm2),
            55 => Ok(Self::PwmAonPwm3),
            56 => Ok(Self::PwmAonPwm4),
            57 => Ok(Self::PwmAonPwm5),
            58 => Ok(Self::OtpCtrlTest0),
            59 => Ok(Self::SysrstCtrlAonBatDisable),
            60 => Ok(Self::SysrstCtrlAonKey0Out),
            61 => Ok(Self::SysrstCtrlAonKey1Out),
            62 => Ok(Self::SysrstCtrlAonKey2Out),
            63 => Ok(Self::SysrstCtrlAonPwrbOut),
            64 => Ok(Self::SysrstCtrlAonZ3Wakeup),
            _ => Err(val),
        }
    }
}

/// Dedicated Pad Selects
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum DirectPads {
    SpiHost0Sd0 = 0,
    SpiHost0Sd1 = 1,
    SpiHost0Sd2 = 2,
    SpiHost0Sd3 = 3,
    SpiDeviceSd0 = 4,
    SpiDeviceSd1 = 5,
    SpiDeviceSd2 = 6,
    SpiDeviceSd3 = 7,
    SysrstCtrlAonEcRstL = 8,
    SysrstCtrlAonFlashWpL = 9,
    SpiDeviceSck = 10,
    SpiDeviceCsb = 11,
    SpiHost0Sck = 12,
    SpiHost0Csb = 13,
}

impl TryFrom<u32> for DirectPads {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::SpiHost0Sd0),
            1 => Ok(Self::SpiHost0Sd1),
            2 => Ok(Self::SpiHost0Sd2),
            3 => Ok(Self::SpiHost0Sd3),
            4 => Ok(Self::SpiDeviceSd0),
            5 => Ok(Self::SpiDeviceSd1),
            6 => Ok(Self::SpiDeviceSd2),
            7 => Ok(Self::SpiDeviceSd3),
            8 => Ok(Self::SysrstCtrlAonEcRstL),
            9 => Ok(Self::SysrstCtrlAonFlashWpL),
            10 => Ok(Self::SpiDeviceSck),
            11 => Ok(Self::SpiDeviceCsb),
            12 => Ok(Self::SpiHost0Sck),
            13 => Ok(Self::SpiHost0Csb),
            _ => Err(val),
        }
    }
}

/// Muxed Pad Selects
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum MuxedPads {
    Ioa0 = 0,
    Ioa1 = 1,
    Ioa2 = 2,
    Ioa3 = 3,
    Ioa4 = 4,
    Ioa5 = 5,
    Ioa6 = 6,
    Ioa7 = 7,
    Ioa8 = 8,
    Iob0 = 9,
    Iob1 = 10,
    Iob2 = 11,
    Iob3 = 12,
    Iob4 = 13,
    Iob5 = 14,
    Iob6 = 15,
    Iob7 = 16,
    Iob8 = 17,
    Iob9 = 18,
    Iob10 = 19,
    Iob11 = 20,
    Iob12 = 21,
    Ioc0 = 22,
    Ioc1 = 23,
    Ioc2 = 24,
    Ioc3 = 25,
    Ioc4 = 26,
    Ioc5 = 27,
    Ioc6 = 28,
    Ioc7 = 29,
    Ioc8 = 30,
    Ioc9 = 31,
    Ioc10 = 32,
    Ioc11 = 33,
    Ioc12 = 34,
    Ior0 = 35,
    Ior1 = 36,
    Ior2 = 37,
    Ior3 = 38,
    Ior4 = 39,
    Ior5 = 40,
    Ior6 = 41,
    Ior7 = 42,
    Ior10 = 43,
    Ior11 = 44,
    Ior12 = 45,
    Ior13 = 46,
}

impl TryFrom<u32> for MuxedPads {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Ioa0),
            1 => Ok(Self::Ioa1),
            2 => Ok(Self::Ioa2),
            3 => Ok(Self::Ioa3),
            4 => Ok(Self::Ioa4),
            5 => Ok(Self::Ioa5),
            6 => Ok(Self::Ioa6),
            7 => Ok(Self::Ioa7),
            8 => Ok(Self::Ioa8),
            9 => Ok(Self::Iob0),
            10 => Ok(Self::Iob1),
            11 => Ok(Self::Iob2),
            12 => Ok(Self::Iob3),
            13 => Ok(Self::Iob4),
            14 => Ok(Self::Iob5),
            15 => Ok(Self::Iob6),
            16 => Ok(Self::Iob7),
            17 => Ok(Self::Iob8),
            18 => Ok(Self::Iob9),
            19 => Ok(Self::Iob10),
            20 => Ok(Self::Iob11),
            21 => Ok(Self::Iob12),
            22 => Ok(Self::Ioc0),
            23 => Ok(Self::Ioc1),
            24 => Ok(Self::Ioc2),
            25 => Ok(Self::Ioc3),
            26 => Ok(Self::Ioc4),
            27 => Ok(Self::Ioc5),
            28 => Ok(Self::Ioc6),
            29 => Ok(Self::Ioc7),
            30 => Ok(Self::Ioc8),
            31 => Ok(Self::Ioc9),
            32 => Ok(Self::Ioc10),
            33 => Ok(Self::Ioc11),
            34 => Ok(Self::Ioc12),
            35 => Ok(Self::Ior0),
            36 => Ok(Self::Ior1),
            37 => Ok(Self::Ior2),
            38 => Ok(Self::Ior3),
            39 => Ok(Self::Ior4),
            40 => Ok(Self::Ior5),
            41 => Ok(Self::Ior6),
            42 => Ok(Self::Ior7),
            43 => Ok(Self::Ior10),
            44 => Ok(Self::Ior11),
            45 => Ok(Self::Ior12),
            46 => Ok(Self::Ior13),
            _ => Err(val),
        }
    }
}

/// Power Manager Wakeup Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerWakeUps {
    SysrstCtrlAonWkupReq = 0,
    AdcCtrlAonWkupReq = 1,
    PinmuxAonPinWkupReq = 2,
    PinmuxAonUsbWkupReq = 3,
    AonTimerAonWkupReq = 4,
    SensorCtrlAonWkupReq = 5,
}

/// Reset Manager Software Controlled Resets
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum ResetManagerSwResets {
    SpiDevice = 0,
    SpiHost0 = 1,
    I2c0 = 2,
}

/// Power Manager Reset Request Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerResetRequests {
    SysrstCtrlAonRstReq = 0,
    AonTimerAonAonTimerRstReq = 1,
}

/// Clock Manager Software-Controlled ("Gated") Clocks.
///
/// The Software has full control over these clocks.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum GateableClocks {
    /// Clock clk_io_div4_peri in group peri
    IoDiv4Peri = 0,
    /// Clock clk_io_div2_peri in group peri
    IoDiv2Peri = 1,
    /// Clock clk_io_peri in group peri
    IoPeri = 2,
}

/// MMIO Region
///
/// MMIO region excludes any memory that is separate from the module
/// configuration space, i.e. ROM, main SRAM, and flash are excluded but
/// retention SRAM, spi_device memory, or usbdev memory are included.
pub const MMIO_BASE_ADDR: usize = 0x40000000;
pub const MMIO_SIZE_BYTES: usize = 0x10000000;
