// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_peri package generated by `tlgen.py` tool

package tl_peri_pkg;

  localparam logic [31:0] ADDR_SPACE_UART0           = 32'h 80000000;
  localparam logic [31:0] ADDR_SPACE_I2C0            = 32'h 80030000;
  localparam logic [31:0] ADDR_SPACE_PWM_AON         = 32'h 80090000;
  localparam logic [31:0] ADDR_SPACE_GPIO            = 32'h 80010000;
  localparam logic [31:0] ADDR_SPACE_SPI_DEVICE      = 32'h 80020000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER        = 32'h 90010000;
  localparam logic [31:0] ADDR_SPACE_PWRMGR_AON      = 32'h 80040000;
  localparam logic [31:0] ADDR_SPACE_RSTMGR_AON      = 32'h 80050000;
  localparam logic [31:0] ADDR_SPACE_CLKMGR_AON      = 32'h 80060000;
  localparam logic [31:0] ADDR_SPACE_PINMUX_AON      = 32'h 800a0000;
  localparam logic [31:0] ADDR_SPACE_OTP_CTRL__CORE  = 32'h a0000000;
  localparam logic [31:0] ADDR_SPACE_OTP_CTRL__PRIM  = 32'h b0001000;
  localparam logic [31:0] ADDR_SPACE_LC_CTRL         = 32'h 800c0000;
  localparam logic [31:0] ADDR_SPACE_AON_TIMER_AON   = 32'h 800b0000;
  localparam logic [31:0] ADDR_SPACE_SYSRST_CTRL_AON = 32'h 80070000;
  localparam logic [31:0] ADDR_SPACE_ADC_CTRL_AON    = 32'h 80080000;
  localparam logic [31:0] ADDR_SPACE_AST             = 32'h 40480000;

  localparam logic [31:0] ADDR_MASK_UART0           = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_I2C0            = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_PWM_AON         = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_GPIO            = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SPI_DEVICE      = 32'h 00001fff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER        = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_PWRMGR_AON      = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_RSTMGR_AON      = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_CLKMGR_AON      = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_PINMUX_AON      = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_OTP_CTRL__CORE  = 32'h 00001fff;
  localparam logic [31:0] ADDR_MASK_OTP_CTRL__PRIM  = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_LC_CTRL         = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_AON_TIMER_AON   = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SYSRST_CTRL_AON = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_ADC_CTRL_AON    = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_AST             = 32'h 000003ff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 17;

  typedef enum int {
    TlUart0 = 0,
    TlI2C0 = 1,
    TlPwmAon = 2,
    TlGpio = 3,
    TlSpiDevice = 4,
    TlRvTimer = 5,
    TlPwrmgrAon = 6,
    TlRstmgrAon = 7,
    TlClkmgrAon = 8,
    TlPinmuxAon = 9,
    TlOtpCtrlCore = 10,
    TlOtpCtrlPrim = 11,
    TlLcCtrl = 12,
    TlAonTimerAon = 13,
    TlSysrstCtrlAon = 14,
    TlAdcCtrlAon = 15,
    TlAst = 16
  } tl_device_e;

  typedef enum int {
    TlMain = 0
  } tl_host_e;

endpackage
